/**
 * Recording domain types — re-exported from @openheaders/core.
 */

export type {
  ConsoleArg,
  ConsoleArgObject,
  ConsoleRecord,
  CookieAttributes,
  DomNode,
  NavigationEntry,
  NetworkRecord,
  NetworkTimingData,
  PageTransition,
  PreprocessedRecording,
  PreprocessOptions,
  PreprocessProgressDetails,
  RawRecordingRecord,
  Recording,
  RecordingEvent,
  RecordingEventData,
  RecordingMetadata,
  RRWebAdd,
  RRWebEvent,
  RRWebInnerData,
  RRWebPlayerConstructor,
  RRWebPlayerInstance,
  RRWebPlayerProps,
  Snapshot,
  StaticResources,
  StorageCookieMetadata,
  StorageRecord,
  TimeEvent,
  TimeEventType,
  WorkflowRecordingEntry,
  WorkflowRecordingFileMetadata,
  WorkflowTag,
} from '@openheaders/core';
